### ISSUE TITLE
Failed to create plugin instance

### ISSUE THREAD

**Issue by wz57c** [swc-project/plugins#116]
I upgraded the plugin from v1.5.25 to next version
find some error
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/13228964/204998182-9ec1b75b-2696-4206-ab27-42f89496abd0.png">
ERROR in ./node_modules/strip-ansi/index.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some(".../node_modules/strip-ansi/index.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "__wbindgen_placeholder__"."__wbindgen_object_drop_ref": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
 @ ./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 163:14-35

ERROR in ./src/main.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some(".../src/main.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "__wbindgen_placeholder__"."__wbindgen_object_drop_ref": unknown import. Expected Function(FunctionType { params: [I32], results: [] })

**Comment by kdy1** [comment]
Does the latest version fails?

cc @kwonoj Do you have any idea?

**Comment by kwonoj** [comment]
Isn't this occurred when we upgraded deps altogether? It still happens after revert?

**Comment by kdy1** [comment]
Yeah it seems like.
@wz57c Can you confirm?

**Comment by Karibash** [comment]
The same error occurred with version 2.5.27 of @swc/plugin-emotion.
When I reverted to version 2.5.21, the error stopped occurring.

**Comment by wz57c** [comment]
> Does the latest version fail?
> 
> cc @kwonoj Do you have any idea?

Yes, I updated to 1.5.29, but there is still an error

**Comment by kdy1** [comment]
@kwonoj I think it's an issue of wasm-pack.
I reverted all dependencies except swc crates

**Comment by kwonoj** [comment]
Where do we use wasm-pack? Plugin itself builds with rust wasm target directly without wasm-pack.

**Comment by kdy1** [comment]
Oh. Then I'm not sure about the cause...

**Comment by kwonoj** [comment]
I just noticed weired

> Some(".../node_modules/strip-ansi/index.js")

Why swc tries to load js file as plugin?

**Comment by wz57c** [comment]
> I just noticed weired
> 
> > Some(".../node_modules/strip-ansi/index.js")
> 
> Why swc tries to load js file as plugin?

No, this is my own dependency, I can remove it, but there is still an error, another error file is my project entry

**Comment by kwonoj** [comment]
I think there should be a minimal reproducible codes, either using codebsandbox or github repo.

**Comment by kostasmanionis** [comment]
Hit this issue with `@swc/plugin-relay` today, wanna say it worked fine a couple of days ago 🤔 🤷 

https://codesandbox.io/s/currying-haze-gwn2z4?file=/index.js

run `yarn start` and you should see the error

**Comment by ogarich89** [comment]
Same issue with @swc/plugin-loadable-components after update > 0.3.25

**Comment by kwonoj** [comment]
I believe this occurs on every plugins with specific versions, so do not need to repeat each individual plugins. We need some investigations when / how this started happen.

**Comment by kwonoj** [comment]
@kdy1 I tried bisect this bit, and looks like something's going on with publish stage. 

These are things I found:

1. Published binary is about 5.2MB
<img width="862" alt="image" src="https://user-images.githubusercontent.com/1210596/208283272-82c1de24-6e61-4459-bdd5-35f79b847f7b.png">
(https://unpkg.com/browse/@swc/plugin-relay@1.5.32/)

2. But if I locally build with `cargo build -p swc_plugin_relay --target wasm32-wasi --release`, it is actuallt ~1.4MB

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1210596/208283280-0427416c-1f38-4d84-89a2-17072473db19.png">

3. Comparing those 2 binaries, it indeed have differences that published binary expects some exports unexpectedly

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1210596/208283298-afb70b8d-11d8-43d8-9d5d-88cee5e0013b.png">

(Left: published plugin binary wat / Right: locally built release build binary wat)

4. Lastly I tried build script myself https://github.com/swc-project/plugins/blob/main/.github/workflows/publish.yml#L41

`cargo build --all --release --target wasm32-wasi`, it indeed generates 5.2MB binary instead of actually expected release build.

Not sure why building pkg individually vs. build all makes this difference.

**Comment by kdy1** [comment]
Oh... I'll check

**Comment by arxpoetica** [comment]
I'm hitting this issue with any version of `@swc/plugin-styled-jsx` from `1.5.26` and up. I've had to lock it to `@swc/plugin-styled-jsx@1.5.25` for it to work. Otherwise see the following error:

```
ERROR in ./src/components/index.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/[...]/src/components/index.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "__wbindgen_placeholder__"."__wbindgen_object_drop_ref": unknown import. Expected Function(FunctionType { params: [I32], results: [] })

webpack 5.75.0 compiled with 1 error in 360 ms
```
